export const TYPE_ICONS: Record<string, string> = {
  normal: "/Type/48px-Normal_icon_SwSh.png",
  fire: "/Type/48px-Fire_icon_SwSh.png",
  water: "/Type/48px-Water_icon_SwSh.png",
  grass: "/Type/48px-Grass_icon_SwSh.png",
  electric: "/Type/48px-Electric_icon_SwSh.png",
  ice: "/Type/48px-Ice_icon_SwSh.png",
  fighting: "/Type/48px-Fighting_icon_SwSh.png",
  poison: "/Type/48px-Poison_icon_SwSh.png",
  ground: "/Type/48px-Ground_icon_SwSh.png",
  flying: "/Type/48px-Flying_icon_SwSh.png",
  psychic: "/Type/48px-Psychic_icon_SwSh.png",
  bug: "/Type/48px-Bug_icon_SwSh.png",
  rock: "/Type/48px-Rock_icon_SwSh.png",
  ghost: "/Type/48px-Ghost_icon_SwSh.png",
  dragon: "/Type/48px-Dragon_icon_SwSh.png",
  dark: "/Type/48px-Dark_icon_SwSh.png",
  steel: "/Type/48px-Steel_icon_SwSh.png",
  fairy: "/Type/48px-Fairy_icon_SwSh.png",
};
